@startuml


class Elevator {

    }

class ElevatorAlgo {

    }

 class buildingClass {
    getMaxFloor()
    getMinFloor()
    getElevator()
    maxFloor
    minFloor
    Object: Elevators
    }

 class ElevatorCalls {

    }
@enduml